export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const LOAD_LETTERS = 'LOAD_LETTERS';
export const SEARCH_BY_LETTER = 'SEARCH_BY_LETTER';
export const HERO_DETAILS = 'HERO_DETAILS';
export const MODAL_VISIBLE = 'MODAL_VISIBLE';
